spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dictionary_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    openai:
      #      api-key: ${spring.ai.openai.api-key}
     # api-key:  sk-F7HULAHnwwcfm8bzoa3ZLAPwZNXbf9GpM0rAsXyLHSH3IHjE # sess-zhIyLnEPonNQLUqpfBfFF2CvBrU5si0Ih2rR8o25 # sk-F7HULAHnwwcfm8bzoa3ZLAPwZNXbf9GpM0rAsXyLHSH3IHjE
     # base-url: https://api.chatanywhere.tech # ${spring.ai.openai.base-url} # https://api.chatanywhere.tech/v1 #
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo-0125 # gpt-3.5-turbo
          temperature: 0.3F
    ollama:
      # ollama API Server 地址
      base-url: http://192.168.3.165:11434
      chat:
        enabled: true
        # 使用的模型名称
        model:
          deepseek-coder-v2:latest #llama3.2:8b
        options:
          temperature: 0.7

mybatis-plus:
#  mapper-locations: classpath*:mapper/*.xml
  mapper-locations: classpath:mapper/*.xml  # 设置 XML 映射文件的位置
  type-aliases-package: com.coderdream.entity  # 设置实体类所在的包
  configuration:
    map-underscore-to-camel-case: true


