spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dictionary_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
#  mapper-locations: classpath*:mapper/*.xml
  mapper-locations: classpath:mapper/*.xml  # 设置 XML 映射文件的位置
  type-aliases-package: com.coderdream.entity  # 设置实体类所在的包
  configuration:
    map-underscore-to-camel-case: true


